---
- hosts: server

  tasks:
  - name: restart server
    command: ./update_code.sh

  - name: halt
    tags:
      - halt
    become: yes
    command: halt

- hosts: clients

  tasks:
  - name: restart client
    command: ./update_code.sh

  - name: reboot
    tags:
      - reboot
    become: yes
    command: reboot

  - name: halt
    tags:
      - halt
    become: yes
    command: halt
